# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqltest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'SQLite.swift', '~> 0.11.5'
   pod 'Alamofire', '~> 4.7'
   pod 'Kingfisher'

  target 'sqltestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sqltestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
